### ISSUE TITLE
Own PlayerShoot does always the same damage (visual)

### ISSUE THREAD

**Issue by ossimc82** [ossimc82/fabiano-swagger-of-doom#1]
Tile says all :P

**Comment by cp-nilly** [comment]
Is there a specific reason one doesn't want this fixed?

For those who want to fix this with their own servers. Look up the hello packet and find where it says **Fp = 0,** . Change that to say **Fp = seed,** .

**Comment by ossimc82** [comment]
no shit, I'll test this, if it works I'll lick your balls :smile:
btw, the wontfix is just because idk how2fix it :D

---

Update: bullshit game...
Nilly where do you live? :smirk:

**Comment by ebf34e12952930cf** [comment]
gg @cp-nilly 
"Wont fix" is probably meant as Fabian couldn't fix it.
