### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by OryxAwakening** [ossimc82/fabiano-swagger-of-doom#10]
http://imgur.com/FwrwZjZ

This is one of the issues

**Comment by ebf34e12952930cf** [comment]
How did it happen/what were you doing?

**Comment by OryxAwakening** [comment]
This occurred multiple times from different thing such as using an ability to using tinctures/effusions or even just making a pet follow you.

This also happens in the realm

**Comment by ossimc82** [comment]
I'll take a look into this, it happens with async methods and stuff, they wont let me catch an exception for some reason, I'll look for a workarround today

**Comment by ossimc82** [comment]
Just tell me if it still appears
