### ISSUE TITLE
Effects2 (Curse, stat buff icons, ...) not showing

### ISSUE THREAD

**Issue by ossimc82** [ossimc82/fabiano-swagger-of-doom#12]
I mean this things:
![Image](http://i.imgur.com/SSOHJgE.png)

**Comment by cp-nilly** [comment]
You still working on this Ossi? If not, I'll take some time to add the needed support.

**Comment by ossimc82** [comment]
Yeah, I am still working on it, but I would very appreciate it if you help out :smiley:
