### ISSUE TITLE
Change IP in client-release.swf

### ISSUE THREAD

**Issue by indiemini** [ossimc82/fabiano-swagger-of-doom#128]
Hi,

I used astrogrep and searched for both "127.0.0.1" and "localhost." But after changing the strings to my server, the client still tries to connect to localhost. Help would be appreciated.

**Comment by kaos00723** [comment]
Use the client updater instead.

**Comment by indiemini** [comment]
How do I change it to my ip though? I saw the mods menu, and I saw that you could set it up for KrazyShank's server, localhost, and c453.pw. 

Thanks in advance!

**Comment by kaos00723** [comment]
Open Form1.cs, click on Form1 and change one of the IP's there to yours. Recompile and run it.

**Comment by indiemini** [comment]
Thanks, I'll give it a shot!

**Comment by indiemini** [comment]
After running the Client Updater, the updated client swf file won't load on chrome ("movie not loaded") and crashes on Flash Projector. Any ideas?

**Comment by kaos00723** [comment]
You're probably using an already modified client or the newest client which won't work.

Use a fresh/untouched 27.3.2 client to start with.

**Comment by indiemini** [comment]
Oh, okay. I think I was using an already modified one. Where can I get an archived, fresh 27.3.2?

**Comment by kaos00723** [comment]
Check here: http://static.drips.pw/rotmg/production/1434669484/

That should be the correct version but I haven't tested it.

**Comment by indiemini** [comment]
TypeError: Error #1090: XML parser failure: element is malformed.

```
at _-Ny::_-200/_-Nw()
at _-Ny::_-200/onComplete()
at _-1Sm::Slot/execute()
at _-1Sm::_-0N3/dispatch()
at _-1l6::_-1Z6/_-0RG()
at _-1l6::_-1Z6/_-01I()
at _-1l6::_-1Z6/onComplete()
at flash.events::EventDispatcher/dispatchEventFunction()
at flash.events::EventDispatcher/dispatchEvent()
at flash.net::URLLoader/onComplete()
```

When I load it into Flash Projector it says that.

**Comment by kaos00723** [comment]
Not sure then bud. Sounds like a screwed up client to me. Are you using Orape mods on it or something? I know fullscreen and some others simply don't work and will give you errors like that.

Unfortunately your only other option is to ask on the Kids-R-Us mpgh forum. ;/

Good luck!

**Comment by indiemini** [comment]
Which mods should I select? When I run the client updater, it requires me to build it with Orape, and Orape won't build unless I select mods. So I chose the disable google analytics mod, figuring it would change the least stuff. Am I using the client updater wrong?

**Comment by kaos00723** [comment]
Disable GA should work since I always build my clients with it.

My only other option is to try this client.swf I just uploaded for you. It's the original from 6/19/15 I downloaded with the client updater.

https://www.dropbox.com/s/jn0nw4rvjmnxd8l/client.swf?dl=0

Hope it helps.

**Comment by indiemini** [comment]
Thanks, it no longer crashes when I rebuild. However, it still tries to connect to localhost rather than my server. I am changing the Localhost ip to my ip, then clicking on the corresponding button. Am I doing something wrong?

EDIT: 
![amidoingitright](https://cloud.githubusercontent.com/assets/6320771/10473247/3d5a8a38-71f7-11e5-85fc-139c9fb0d0fe.PNG)

**Comment by kaos00723** [comment]
192.168.x.x is a local network IP address. :)

You need to enter your outside IP address. If you don't have a static IP then you'll need to use a service such as noip.com if you plan on running it from your own PC.

Otherwise you'll need something like Hamachi or to rent a VPS or similar.

**Comment by indiemini** [comment]
I was actually trying to set it up for local network so that my friends could play if they were at my house :p 

Anyhow, I got it working. Turns out, Windows Firewall hates me. Resolved, thanks so much for you help!

**Comment by indiemini** [comment]
Update: Priests appear to be really bugged, because the range and effect of almost every tome is significantly larger than each should be. When trying to use the tomes, the client lags out because it's trying to display too many particles, or something like that. Either way, using a tome makes the client unusable until you reload it. Thankfully, everything seems to be working perfectly otherwise.

EDIT: nvm, im stupid. wismod is cool xD
