### ISSUE TITLE
log4net:ERROR when using mono on Debian 8.3

### ISSUE THREAD

**Issue by tylerspencer237** [ossimc82/fabiano-swagger-of-doom#131]
I an getting the log4net error when I try to run both the wServer.exe and server.exe on my Debian 8.3 server. I rebuilt using Visual Studio a couple of times, checked the mysql and this error still occurs. If anyone has experienced this and fixed it, I would appreciate the help.

**Comment by ebf34e12952930cf** [comment]
What is the error?

**Comment by tylerspencer237** [comment]
![server](https://cloud.githubusercontent.com/assets/13008477/13161861/54858dee-d655-11e5-8cbe-17ae4deb2fca.PNG)
![wserver](https://cloud.githubusercontent.com/assets/13008477/13161862/5497c4a0-d655-11e5-80eb-2dbbecd9ed59.PNG)
Both of them give the same error

**Comment by ossimc82** [comment]
Try using just a "ConsoleAppender" instead of a "ColoredConsoleAppender" in the log4net config file, that should fix the issue

**Comment by tylerspencer237** [comment]
wServer now does a "System.MissingMethodException: Method 'Array.Empty' not found.
  at wServer.logic.BehaviorDb..ctor (wServer.realm.RealmManager manager) <0x41d0bcd0 + 0x02ff3> in <filename unknown>:0
  at wServer.realm.RealmManager.Initialize () <0x4052c7f0 + 0x000d3> in <filename unknown>:0
  at wServer.Program.Main (System.String[] args) <0x411b6400 + 0x0039b> in <filename unknown>:0"

**Comment by tylerspencer237** [comment]
As mentioned above, here is a screenshot of what I talked about. 
![server](https://cloud.githubusercontent.com/assets/13008477/13199956/bfb7901c-d7ea-11e5-98b5-b93272e818ea.PNG)

**Comment by tylerspencer237** [comment]
This fixed the "ColoredConsole" error
