### ISSUE TITLE
Admin rights

### ISSUE THREAD

**Issue by raychiao** [ossimc82/fabiano-swagger-of-doom#14]
is there a way to make an account administrator for the server? whenever i type a specified command it gives a "no permission" error

**Comment by ebf34e12952930cf** [comment]
Rank 3 in the database

**Comment by raychiao** [comment]
database.cs?

**Comment by ossimc82** [comment]
Look at the ranks page on the github wiki or on mpgh for help, thanks.

**Comment by raychiao** [comment]
are you going to followup the v24.0.0?

**Comment by ossimc82** [comment]
24.0.0 what?

**Comment by raychiao** [comment]
the new version of rotmg

**Comment by ossimc82** [comment]
Can you count to 30? 27 comes after 24 my friend

**Comment by raychiao** [comment]
i have a question, is it the same way importing maps and new items like the other servers or there has to be another way?
