### ISSUE TITLE
Custom Items disabled 

### ISSUE THREAD

**Issue by VeraXon** [ossimc82/fabiano-swagger-of-doom#20]
Could u turn them on? would be better for me i think for the others too
other wise the custom items appear as a errorbox then making the game crash

**Comment by C453** [comment]
There is already an open issue concerning this; please post there

**Comment by GhostMaree** [comment]
"Custom Items disabled" its not discabled
before orape -> use rabcdasm  to add items to client (fresh client) -> client updater
and done :3
