### ISSUE TITLE
Global news issue.

### ISSUE THREAD

**Issue by xxpussylordxx** [ossimc82/fabiano-swagger-of-doom#22]
I've tried everything and the client just bugs and doesn't load.

**Comment by ossimc82** [comment]
You need to provide some more information, otherwise noone will be able to help you...

**Comment by xxpussylordxx** [comment]
I edit the globalnews.txt pretty much just replace some text and then the client just doesnt load at all its all that happens nothing else but that affects it. I also activated the globalnews in the db didnt work either

**Comment by ossimc82** [comment]
They work, I bet you removed a ``"`` by mistake
