### ISSUE TITLE
Packages aren't sent to vault

### ISSUE THREAD

**Issue by xxpussylordxx** [ossimc82/fabiano-swagger-of-doom#37]
Like i add it on the database it shows up but when i go to vault its not there

**Comment by xxpussylordxx** [comment]
It throws this error in the server.exe 
![gxbxhim](https://cloud.githubusercontent.com/assets/12571770/7802381/02b26386-02fa-11e5-8815-0679f80b4149.png)

**Comment by xxpussylordxx** [comment]
and then after a bit this gets sent
![fbiiqcb](https://cloud.githubusercontent.com/assets/12571770/7802395/3bbaafc6-02fa-11e5-98ef-c4c6a0c54fd3.png)

**Comment by ossimc82** [comment]
I'll look into it tomorrow

**Comment by BlackRayquaza** [comment]
Maybe your contents syntax is wrong.
Here is an example:
{"items":[3276,3276,3276,3276,3276,3276,3276,3276,3276,3276],"charSlots":0,"vaultChests":0}

**Comment by xxpussylordxx** [comment]
I forgot to check that let me check it

**Comment by xxpussylordxx** [comment]
this is what i see 

![](http://i.imgur.com/nR74YRs.png)

Am i supposed to see something extra?

**Comment by xxpussylordxx** [comment]
It worked the way black said. I have no brain. :L

**Comment by BlackRayquaza** [comment]
@xxpussylordxx Fixed?
@ossimc82 :+1:

**Comment by ossimc82** [comment]
I guess yes xD
