### ISSUE TITLE
World Server Playerhit Error

### ISSUE THREAD

**Issue by kaos00723** [ossimc82/fabiano-swagger-of-doom#38]
These error messages are sometimes output to the wServer console when engaged with enemies:

Can't register playerhit.300070 - 2
Can't register playerhit.300861 - 2

**Comment by ossimc82** [comment]
Its not an error, its just a warning that the client got hit by a projectile that does not exist anymore

**Comment by kaos00723** [comment]
Ok thanks, red text in the console always makes me a little antsy. ;)

Also want to say you are doing an amazing job. I really appreciate what you are doing here.

**Comment by ebf34e12952930cf** [comment]
@ossimc82 They could/should be yellow text as they are not errors.
