### ISSUE TITLE
Email Verification not Working

### ISSUE THREAD

**Issue by kaos00723** [ossimc82/fabiano-swagger-of-doom#41]
When verifyEmail is set to true in the config files, the following error appears in the console when someone clicks the "Send Verification Email" link in the popup window.

![Imgur](http://i.imgur.com/cBiIIPW.png)

Also, nothing happens when you click on account and "Email not verified. Click here to resend email." on the title page. It says "sent" but since sendVerifyEmail.cs is empty nothing actually happens.

**Comment by xxpussylordxx** [comment]
you need to set it up correctly it works for me

**Comment by kaos00723** [comment]
Both config files set to true for email verification. I've tried using SMTP info for both a Yahoo account and Gmail account. Is there more to it than just editing the two config files with correct info?

**Comment by kaos00723** [comment]
verifyEmail:true
serverEmail:MyEmail
serverEmailPassword:Password
smtpHost:smtp.mail.yahoo.com
smtpPort:587

This is what I have in the config settings so I must be missing something. ;/

**Comment by kaos00723** [comment]
Looks like Yahoo wanted port 465 instead of 587. The main error is gone so I closed this.
