### ISSUE TITLE
RemoteTextures don't work

### ISSUE THREAD

**Issue by xxpussylordxx** [ossimc82/fabiano-swagger-of-doom#42]
if it does can u guys help a homie out?

**Comment by SirAnuse** [comment]
just look at server > picture > get.cs

figure it out

**Comment by xxpussylordxx** [comment]
ok ty

**Comment by xxpussylordxx** [comment]
i cant do it ;-;

**Comment by SirAnuse** [comment]
im pretty sure it's like this:

<RemoteTexture>
  <Id>draw:{id{</Id>
<RemoteTexture>

btw u gotta change the link to realmofthemadgodhrd.appspot.com (I think)

**Comment by xxpussylordxx** [comment]
Still having issues :(

**Comment by kaos00723** [comment]
Update to latest commit. Create a new directory called "texture" under Server. Add a sample texture called test.png.

Go to: http://yourserver.com/picture/get?id=test

If your texture shows then you can at least narrow it down to the XML syntax being the problem.

**Comment by xxpussylordxx** [comment]
yeah it doesnt work it wont even grab it from me maybe fab removed remote textures since he wanted a prod only source

**Comment by kaos00723** [comment]
If you don't see a texture after following my instructions then you did something wrong because the server definitely pulls and displays them. Make sure you put the texture folder in the correct directory.

**Comment by xxpussylordxx** [comment]
I did but theres a bunch of commented lines in the get.cs when i uncomment them its just a bunch of errors i don't know how to fix. if it works for u using fabs can you send me your get.cs or maybe your skype to work this out

**Comment by kaos00723** [comment]
You didn't update to latest commit. :) These instructions are only valid if you have the experimental build commit from yesterday. They also worked before the commit but pulling them from a local directory makes much more sense now.

**Comment by xxpussylordxx** [comment]
Ok it works when i look for the image how do you have your xml set up?

**Comment by xxpussylordxx** [comment]
<RemoteTexture>
<Id draw:{id}</Id>
</RemoteTexture>
 and
