### ISSUE TITLE
Custom Enemies

### ISSUE THREAD

**Issue by ashley-dv** [ossimc82/fabiano-swagger-of-doom#43]
Even when I use an existing texture it won't show up lel

doesn't say anything about unknown type but neither does it say anything about errors... it exists, just an invisible texture.

Not sure if disabled or whut

UPDATE: It certainly isn't a missing texture, not even invisible, because it doesn't show the enemy's shadow.

**Comment by xxpussylordxx** [comment]
ive had invisible projectiles did u add the ext="true" part? i think its ext i dont remember

**Comment by SirAnuse** [comment]
updated

**Comment by ashley-dv** [comment]
Anything in particular that may be causing this?

**Comment by ashley-dv** [comment]
UPDATE: Found out how to add custom enemies, nevermind.
