### ISSUE TITLE
Destructible Walls

### ISSUE THREAD

**Issue by ebf34e12952930cf** [ossimc82/fabiano-swagger-of-doom#50]
http://i.gyazo.com/a94db293e78ca099c243f116f21e1c25.mp4

// Im back!

⊂ヽ
　 ＼＼ ＿
　　 ＼(　••) F
　　　 <　⌒ヽ A
　　　/ 　 へ＼ B
　　 /　　/　＼＼ U
　　 ﾚ　ノ　　 ヽつ 
　　/　/ L
　 /　/| O
　(　(ヽ U
　|　|、＼. S
　| 丿 ＼ ⌒)
　| |　　) /
ノ )　　Lﾉ
(／

**Comment by xxpussylordxx** [comment]
Whats this supposed to explain?

**Comment by ebf34e12952930cf** [comment]
@xxpussylordxx Anyone good decent eyes should be able to see that 1 projectile does damage twice....

**Comment by ossimc82** [comment]
> @xxpussylordxx Anyone good decent eyes should be able to see that 1 projectile does damage twice....

Its just showing the damage twice, it does not do the damage twice :cat:
