### ISSUE TITLE
Priest projectiles pass through destructible objects

### ISSUE THREAD

**Issue by kaos00723** [ossimc82/fabiano-swagger-of-doom#53]
Wizard projectiles hit destructible walls and then vanish like normal after doing damage.

Priest projectiles pass through destructible walls after doing damage and keep going. Not sure if intended or bug.

Have not tested other classes.

**Comment by ebf34e12952930cf** [comment]
Wands have piercing projectiles? _sarcasm_

**Comment by kaos00723** [comment]
No idea, tested with T0 staff and lvl 2 priest. Was able to hit enemies on other side of destructible walls without breaking them since they pass through.

**Comment by kaos00723** [comment]
Realmeye says they have pierce since v25.0.0. So guess this is normal.

**Comment by kaos00723** [comment]
Yeah, last time I played was over 2 years ago so I really don't know what changed since then. Interesting dynamic though for Priests.
