### ISSUE TITLE
Non-Named Accounts

### ISSUE THREAD

**Issue by VeraXon** [ossimc82/fabiano-swagger-of-doom#62]
Non-Named accounts in server can speak. in prod they can't.

**Comment by ashley-dv** [comment]
nobody cares about this if anything un-named people being able to speak is a good thing

close pl0x

**Comment by kaos00723** [comment]
People obviously do care about it if an issue was created. If it's not working as intended then it's a bug/needs implementation. If 10 people have the same generated name and they all talk how well do you think that will go?
