### ISSUE TITLE
Pet Fuse

### ISSUE THREAD

**Issue by VeraXon** [ossimc82/fabiano-swagger-of-doom#63]
If fusing pets and the pets will evolve, the new pet is having still the old skin untill you go in a other world. in prod its auto updating

**Comment by BlackRayquaza** [comment]
Pls don't say shit
https://youtu.be/Ir7QFPC5yZ4?t=3m58s

**Comment by ossimc82** [comment]
Pls don't say shit
https://youtu.be/Ir7QFPC5yZ4?t=3m58s
