### ISSUE TITLE
disablepet and /eff 36 don't work properly

### ISSUE THREAD

**Issue by DylanQ** [ossimc82/fabiano-swagger-of-doom#67]
it seems that when i add the effect 36 or even use disablepet in a command it only adds the icon but the pet acts as normal. It seems only to work from bullets :c

**Comment by ossimc82** [comment]
Who the fuck needs that???

**Comment by ebf34e12952930cf** [comment]
Rekt

**Comment by DylanQ** [comment]
Rip proper spectate command
