### ISSUE TITLE
Smooth Wandering/Following

### ISSUE THREAD

**Issue by ashley-dv** [ossimc82/fabiano-swagger-of-doom#79]
On Fabiano Swagger of Doom (and every other private server), the wandering and following is pretty... spastic. I noticed this in a Pirate Cave, and the pirates really jolt instead of smoothly following you like in prod. Wouldn't call this an issue, but it's just kind of a vanity thing.

**Comment by ossimc82** [comment]
They are not that spastic if you change the speed
