### ISSUE TITLE
Game doesn't start

### ISSUE THREAD

**Issue by Tsukabi** [ossimc82/fabiano-swagger-of-doom#99]
The game doesn't start, there is the music, and an "infinity loading screen"...

**Comment by Sebafra-dev** [comment]
for me game start...

**Comment by Tsukabi** [comment]
What do you use for open the server ? Web browser, or Flash projector ?

**Comment by Sebafra-dev** [comment]
flash projector

**Comment by Sebafra-dev** [comment]
u get any errors in wserver or server?

**Comment by Tsukabi** [comment]
Nono, nothing errors. But the game remain in the loading screen for ever...

**Comment by ebf34e12952930cf** [comment]
@Tsukabi If you plan on using flash projector, make sure you have installed the latest [Flash](https://get.adobe.com/flashplayer/?no_redirect), and the latest [Flash Projector (download)](https://fpdownload.macromedia.com/pub/flashplayer/updaters/18/flashplayer_18_sa.exe). Make sure the client-release.swf (or something else if you renamed it) is in your trusted locations (Settings -> Advanced -> Trusted Locations).
![](http://i.imgur.com/5qlM0ZR.png)
If it still doesn't work delete all your projector settings (Settings -> Delete everything)
![](http://i.imgur.com/WgtQvSG.png)
And make sure you have the latest source.

**Comment by ossimc82** [comment]
I guess this is resolved
